(function(root,factory){var api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.MGNotificationEngine=api;})(typeof window!=="undefined"?window:this,function(){
"use strict";
var PRIORITY={critical:4,high:3,medium:2,low:1};
function empty(){return{version:1,items:[],ids:{},projectProgress:{},weeklyKey:""};}
function load(raw){var s=empty();try{var x=typeof raw==="string"?JSON.parse(raw):raw;if(x&&typeof x==="object"){s.items=Array.isArray(x.items)?x.items:[];s.ids=x.ids&&typeof x.ids==="object"?x.ids:{};s.projectProgress=x.projectProgress&&typeof x.projectProgress==="object"?x.projectProgress:{};s.weeklyKey=typeof x.weeklyKey==="string"?x.weeklyKey:"";s.version=1;}}catch(e){}s.items.forEach(function(x){if(x&&x.id)s.ids[x.id]=true;});return s;}
function add(state,item){if(!item||!item.id||state.ids[item.id])return null;item=Object.assign({read:false,createdAt:new Date().toISOString()},item);state.ids[item.id]=true;state.items.unshift(item);if(state.items.length>300)state.items.length=300;return item;}
function dayNumber(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(s||"")))return null;var a=s.split("-").map(Number),d=new Date(Date.UTC(a[0],a[1]-1,a[2]));if(d.getUTCFullYear()!==a[0]||d.getUTCMonth()+1!==a[1]||d.getUTCDate()!==a[2])return null;return Math.floor(d.getTime()/86400000);}
function diff(from,to){var a=dayNumber(from),b=dayNumber(to);return a===null||b===null?null:b-a;}
function detectSchedule(state,tasks,asOf,planned,actual,enabled){var created=[];(tasks||[]).forEach(function(x){if(!x||x.status==="completed"||!x.id)return;var left=diff(asOf,x.plannedEnd),p=x.projectName||"";if(left!==null){if(left<0&&enabled.overdue){var a=add(state,{id:"overdue:"+x.id+":"+x.plannedEnd,type:"overdue",taskId:x.id,projectId:x.project||"",taskName:x.name||"",projectName:p,days:Math.abs(left),priority:"critical"});if(a)created.push(a);}else if(left===0&&enabled.deadline){var b=add(state,{id:"due-today:"+x.id+":"+x.plannedEnd,type:"dueToday",taskId:x.id,projectId:x.project||"",taskName:x.name||"",projectName:p,days:0,priority:"high"});if(b)created.push(b);}else if(enabled.deadline&&[7,3,1].indexOf(left)>=0){var c=add(state,{id:"deadline:"+x.id+":"+x.plannedEnd+":"+left,type:"deadline",taskId:x.id,projectId:x.project||"",taskName:x.name||"",projectName:p,days:left,priority:left===7?"low":"medium"});if(c)created.push(c);}}
if(enabled.behind&&x.plannedStart&&x.plannedEnd&&dayNumber(x.plannedStart)!==null&&dayNumber(x.plannedEnd)!==null&&dayNumber(x.plannedStart)<=dayNumber(x.plannedEnd)){var pv=planned(x,asOf),av=actual(x);if(pv!==null&&pv!==undefined&&av<pv-5){var d=add(state,{id:"behind:"+x.id+":"+x.plannedEnd,type:"behind",taskId:x.id,projectId:x.project||"",taskName:x.name||"",projectName:p,actual:av,planned:pv,priority:"high"});if(d)created.push(d);}}});return created;}
function addCompletion(state,task,projectName,at){if(!task||!task.id)return null;return add(state,{id:"completed:"+task.id,type:"completed",taskId:task.id,projectId:task.project||"",taskName:task.name||"",projectName:projectName||"",priority:"low",createdAt:at||new Date().toISOString()});}
function updateMilestones(state,projects,getProgress,at,enabled){var created=[];(projects||[]).forEach(function(p){if(!p||!p.id)return;var current=Math.max(0,Math.min(100,Number(getProgress(p.id))||0)),key=String(p.id),previous=state.projectProgress[key];if(previous===undefined||previous===null){state.projectProgress[key]=current;return;}[25,50,75,100].forEach(function(mark){if(enabled&&previous<mark&&current>=mark){var a=add(state,{id:"milestone:"+key+":"+mark,type:"milestone",projectId:key,projectName:p.name||"",milestone:mark,priority:"low",createdAt:at||new Date().toISOString()});if(a)created.push(a);}});state.projectProgress[key]=current;});return created;}
function permissionState(supported,permission,enabled){if(!supported)return{status:"unsupported",help:"permissionUnsupported",enabled:false};if(permission==="denied")return{status:"denied",help:"permissionDenied",enabled:false};if(permission==="granted")return{status:"granted",help:"permissionGrantedHelp",enabled:!!enabled};return{status:"default",help:"permissionDefault",enabled:false};}
return{PRIORITY:PRIORITY,empty:empty,load:load,add:add,dayNumber:dayNumber,diff:diff,detectSchedule:detectSchedule,addCompletion:addCompletion,updateMilestones:updateMilestones,permissionState:permissionState};
});
